services:
  master:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master"
    image: "citusdata/citus:12.1"
    ports: ["${COORDINATOR_EXTERNAL_PORT:-5432}:5432"]
    labels: ["com.citusdata.role=Master"]
    environment: &AUTH
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      PGUSER: "${POSTGRES_USER:-postgres}"
      PGPASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
    volumes:
      - ./data/coordinator-data:/var/lib/postgresql/data
  worker_1:
    image: "citusdata/citus:12.1"
    labels: ["com.citusdata.role=Worker"]
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_worker_1"
    depends_on: [manager]
    environment: *AUTH
    command: "/wait-for-manager.sh"
    volumes:
      - ./data/healthcheck-volume:/healthcheck
      - ./data/worker-data-1:/var/lib/postgresql/data
    
  worker_2:
    image: "citusdata/citus:12.1"
    labels: ["com.citusdata.role=Worker"]
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_worker_2"
    depends_on: [manager]
    environment: *AUTH
    command: "/wait-for-manager.sh"
    volumes:
      - ./data/healthcheck-volume:/healthcheck
      - ./data/worker-data-2:/var/lib/postgresql/data
    
  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - ./data/healthcheck-volume:/healthcheck
    depends_on: [master]
    environment: *AUTH
volumes:
  healthcheck-volume:
